word_categories = {
        "animals": [
            "elephant",
            "giraffe",
            "kangaroo",
            "dolphin",
            "penguin",
            "cheetah",
            "octopus",
            "crocodile",
            "squirrel",
            "butterfly",
        ],
        "countries": [
            "argentina",
            "brazil",
            "canada",
            "denmark",
            "egypt",
            "france",
            "germany",
            "hungary",
            "italy",
            "japan",
        ],
        "fruits": [
            "apple",
            "banana",
            "cherry",
            "strawberry",
            "elderberry",
            "fig",
            "grapefruit",
            "honeydew",
            "kiwi",
            "lemon",
        ],
        "professions": [
            "architect",
            "baker",
            "carpenter",
            "dentist",
            "engineer",
            "farmer",
            "geologist",
            "hairdresser",
            "illustrator",
            "judge",
        ],
    }